In [1]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv("C:\\Users\\saivi\\Hackathon\\tmdb_5000_movies.csv\\tmdb_5000_movies.csv")
credits = pd.read_csv("C:\\Users\\saivi\\Hackathon\\tmdb_5000_credits.csv\\tmdb_5000_credits.csv")

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits,on="title")

In [8]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [11]:
movies["original_language"].value_counts()

en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: original_language, dtype: int64

In [13]:
movies = movies[["movie_id","title","overview","genres","keywords","cast","crew"]]

In [19]:
movies.isnull()

      movie_id  title  overview  genres  keywords   cast   crew
0        False  False     False   False     False  False  False
1        False  False     False   False     False  False  False
2        False  False     False   False     False  False  False
3        False  False     False   False     False  False  False
4        False  False     False   False     False  False  False
...        ...    ...       ...     ...       ...    ...    ...
4804     False  False     False   False     False  False  False
4805     False  False     False   False     False  False  False
4806     False  False     False   False     False  False  False
4807     False  False     False   False     False  False  False
4808     False  False     False   False     False  False  False

[4809 rows x 7 columns]

In [20]:
movies.sum()

C:\Users\saivi\AppData\Local\Temp\ipykernel_4576\2790600498.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  movies.sum()

movie_id                                            274692828
title       AvatarPirates of the Caribbean: At World's End...
genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
dtype: object

In [21]:
movies.iloc[2].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]'

In [101]:
movies.dropna(1)

C:\Users\saivi\AppData\Local\Temp\ipykernel_4576\3538030731.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  movies.dropna(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In the 22nd century, a paraplegic Marine is d...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In the 22nd century, a paraplegic Marine is d..."
1,285,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain Barbossa, long believed to be dead, h..."
2,206647,Spectre,[A cryptic message from Bondâ€™s past sends him ...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],[A cryptic message from Bondâ€™s past sends him ...
3,49026,The Dark Knight Rises,[Following the death of District Attorney Harv...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],[Following the death of District Attorney Harv...
4,49529,John Carter,"[John Carter is a war-weary, former military c...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John Carter is a war-weary, former military c..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,[El Mariachi just wants to play his guitar and...,"[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],[El Mariachi just wants to play his guitar and...
4805,72766,Newlyweds,[A newlywed couple's honeymoon is upended by t...,"[Comedy, Romance]",[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],[A newlywed couple's honeymoon is upended by t...
4806,231617,"Signed, Sealed, Delivered","[""Signed, Sealed, Delivered"" introduces a dedi...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed, Sealed, Delivered"" introduces a dedi..."
4807,126186,Shanghai Calling,[When ambitious New York attorney Sam is sent ...,[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],[When ambitious New York attorney Sam is sent ...
4808,25975,My Date with Drew,[Ever since the second grade when he first saw...,[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],[Ever since the second grade when he first saw...

In [23]:
def change(obj):
    X = []
    for i in obj:
        X.append(i["name"])
        return X

In [25]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [34]:
def convert(obj):
    X = []
    for i in ast.literal_eval(obj):
        X.append(i['name'])
    return X

In [35]:
movies['genres'] = movies['genres'].apply(convert)

In [36]:
movies.iloc[2].keywords

'[{"id": 470, "name": "spy"}, {"id": 818, "name": "based on novel"}, {"id": 4289, "name": "secret agent"}, {"id": 9663, "name": "sequel"}, {"id": 14555, "name": "mi6"}, {"id": 156095, "name": "british secret service"}, {"id": 158431, "name": "united kingdom"}]'

In [37]:
movies['keywords'] = movies['keywords'].apply(convert)

In [38]:
movies['cast'][2]

'[{"cast_id": 1, "character": "James Bond", "credit_id": "52fe4d22c3a368484e1d8d6b", "gender": 2, "id": 8784, "name": "Daniel Craig", "order": 0}, {"cast_id": 14, "character": "Blofeld", "credit_id": "54805866c3a36829ab002592", "gender": 2, "id": 27319, "name": "Christoph Waltz", "order": 1}, {"cast_id": 13, "character": "Madeleine", "credit_id": "546f934fc3a3682f9a002ca5", "gender": 1, "id": 121529, "name": "L\\u00e9a Seydoux", "order": 2}, {"cast_id": 10, "character": "M", "credit_id": "53e86503c3a368399c0031f0", "gender": 2, "id": 5469, "name": "Ralph Fiennes", "order": 3}, {"cast_id": 17, "character": "Lucia", "credit_id": "54805920c3a36829ae0022c5", "gender": 1, "id": 28782, "name": "Monica Bellucci", "order": 4}, {"cast_id": 8, "character": "Q", "credit_id": "52fe4d22c3a368484e1d8d87", "gender": 2, "id": 17064, "name": "Ben Whishaw", "order": 5}, {"cast_id": 11, "character": "Moneypenny", "credit_id": "53e8650cc3a368399c0031f4", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 6}, {"cast_id": 16, "character": "Hinx", "credit_id": "5480590f9251416e7b0022f4", "gender": 2, "id": 543530, "name": "Dave Bautista", "order": 7}, {"cast_id": 15, "character": "C", "credit_id": "548058ffc3a36829a7002511", "gender": 2, "id": 125660, "name": "Andrew Scott", "order": 8}, {"cast_id": 19, "character": "Tanner", "credit_id": "5480593cc3a36829ae0022ca", "gender": 2, "id": 139549, "name": "Rory Kinnear", "order": 9}, {"cast_id": 23, "character": "Mr. White", "credit_id": "5517b3849251416f0d0032c8", "gender": 2, "id": 2244, "name": "Jesper Christensen", "order": 10}, {"cast_id": 24, "character": "Marco Sciarra", "credit_id": "5517b398c3a36862fc002df6", "gender": 0, "id": 1381616, "name": "Alessandro Cremona", "order": 11}, {"cast_id": 25, "character": "Estrella", "credit_id": "5517b3c49251412c1e00180b", "gender": 1, "id": 929937, "name": "Stephanie Sigman", "order": 12}, {"cast_id": 49, "character": "Mexican Man in Lift", "credit_id": "5664561cc3a3682bd0007fc8", "gender": 0, "id": 87265, "name": "Tenoch Huerta", "order": 13}, {"cast_id": 50, "character": "Mexican Woman in Lift", "credit_id": "5664561dc3a3682be9008dc6", "gender": 1, "id": 983710, "name": "Adriana Paz", "order": 14}, {"cast_id": 180, "character": "Gallo", "credit_id": "56fddbacc3a36821b6000aca", "gender": 2, "id": 1385592, "name": "Domenico Fortunato", "order": 15}, {"cast_id": 51, "character": "Gallo\'s Accomplice", "credit_id": "5664561dc3a3682bd8008fbe", "gender": 0, "id": 1545546, "name": "Marco Zingaro", "order": 16}, {"cast_id": 52, "character": "Gallo\'s Accomplice", "credit_id": "5664561d9251412ad300870b", "gender": 2, "id": 1545547, "name": "Stefano Elfi DiClaudia", "order": 17}, {"cast_id": 181, "character": "Q\'s Assistant", "credit_id": "56fddc319251412a4d0009f9", "gender": 0, "id": 122556, "name": "Ian Bonar", "order": 18}, {"cast_id": 182, "character": "Moneypenny\'s Boyfriend", "credit_id": "56fddc66c3a36821b6000b04", "gender": 2, "id": 1599239, "name": "Tam Williams", "order": 19}, {"cast_id": 183, "character": "Blofeld\'s London Helicopter Pilot", "credit_id": "56fddc989251412a56000a85", "gender": 2, "id": 1599241, "name": "Richard Banham", "order": 20}, {"cast_id": 184, "character": "SC019 Police Commander", "credit_id": "56fddccf9251412a4b000b5d", "gender": 2, "id": 230681, "name": "Pip Carter", "order": 21}, {"cast_id": 185, "character": "SC019 Police Officer", "credit_id": "56fddce6c3a36821ae000b45", "gender": 2, "id": 30446, "name": "Simon Lenagan", "order": 22}, {"cast_id": 27, "character": "Priest", "credit_id": "5517b4f69251416efe003370", "gender": 2, "id": 48377, "name": "Alessandro Bressanello", "order": 23}, {"cast_id": 38, "character": "Moreau", "credit_id": "56486811c3a3682605006adc", "gender": 0, "id": 578512, "name": "Marc Zinga", "order": 24}, {"cast_id": 39, "character": "Vogel", "credit_id": "56486820c3a368261a006de7", "gender": 0, "id": 1093974, "name": "Brigitte Millar", "order": 25}, {"cast_id": 41, "character": "Abrika", "credit_id": "564868a09251413ad7006da5", "gender": 2, "id": 89624, "name": "Adel Bencherif", "order": 26}, {"cast_id": 186, "character": "Blofeld\'s Right Hand Man", "credit_id": "56fddd5a9251412a42000b52", "gender": 2, "id": 1129783, "name": "Gediminas Adomaitis", "order": 27}, {"cast_id": 42, "character": "Lorenzo", "credit_id": "564868c5c3a368260c006ee4", "gender": 0, "id": 226388, "name": "Peppe Lanzetta", "order": 28}, {"cast_id": 187, "character": "Francesco", "credit_id": "56fddd9cc3a36821a4000b5b", "gender": 2, "id": 1299312, "name": "Francesco Arca", "order": 29}, {"cast_id": 188, "character": "Marco", "credit_id": "56fdddb79251412a50000aad", "gender": 2, "id": 124628, "name": "Matteo Taranto", "order": 30}, {"cast_id": 189, "character": "Palazzo Security", "credit_id": "56fdddd69251412a56000ac6", "gender": 2, "id": 1562103, "name": "Emilio Aniba", "order": 31}, {"cast_id": 190, "character": "Guerra", "credit_id": "56fdddf19251412a50000ac1", "gender": 2, "id": 1474616, "name": "Benito Sagredo", "order": 32}, {"cast_id": 191, "character": "Businessman", "credit_id": "56fdde0d9251416cc200004c", "gender": 2, "id": 1247684, "name": "Dai Tabuchi", "order": 33}, {"cast_id": 192, "character": "Businessman", "credit_id": "56fdde1bc3a36821b1000ba8", "gender": 2, "id": 1599245, "name": "George Lasha", "order": 34}, {"cast_id": 193, "character": "Businessman", "credit_id": "56fdde259251412a42000b93", "gender": 0, "id": 1599247, "name": "Sargon Yelda", "order": 35}, {"cast_id": 194, "character": "Businessman", "credit_id": "56fdde9fc3a36821b6000ba0", "gender": 2, "id": 1599251, "name": "Andy Cheung", "order": 36}, {"cast_id": 195, "character": "Marshall", "credit_id": "56fddeb29251412a50000af4", "gender": 2, "id": 1599252, "name": "Erick Hayden", "order": 37}, {"cast_id": 196, "character": "Valerian", "credit_id": "56fddec8c3a36821ab000c19", "gender": 2, "id": 1599253, "name": "Oleg Mirochnikov", "order": 38}, {"cast_id": 197, "character": "Fiat Driver", "credit_id": "56fddef89251412a47000a79", "gender": 2, "id": 123548, "name": "Antonio Salines", "order": 39}, {"cast_id": 198, "character": "Street Sweeper", "credit_id": "56fddf109251416cc2000086", "gender": 2, "id": 1599254, "name": "Miloud Mourad Benamara", "order": 40}, {"cast_id": 199, "character": "Chairman", "credit_id": "56fddf4a9251412a42000bcf", "gender": 2, "id": 1599255, "name": "Gido Schimanski", "order": 41}, {"cast_id": 200, "character": "Head of Nation", "credit_id": "56fddf69c3a36821a7000b12", "gender": 0, "id": 1404403, "name": "Nigel Barber", "order": 42}, {"cast_id": 201, "character": "Head of Nation", "credit_id": "56fddf7fc3a36821b1000c0d", "gender": 2, "id": 74415, "name": "Patrice Naiambana", "order": 43}, {"cast_id": 202, "character": "Head of Nation", "credit_id": "56fddf89c3a368219d000adb", "gender": 2, "id": 1599256, "name": "Stephane Cornicard", "order": 44}, {"cast_id": 203, "character": "Head of Nation", "credit_id": "56fddf929251412a56000b29", "gender": 2, "id": 1599257, "name": "Gary Fannin", "order": 45}, {"cast_id": 204, "character": "Head of Nation", "credit_id": "56fddf9cc3a36821ae000be1", "gender": 2, "id": 1599258, "name": "Sadao Ueda", "order": 46}, {"cast_id": 205, "character": "Head of Nation", "credit_id": "56fddfb99251412a50000b30", "gender": 0, "id": 1599259, "name": "Phillip Law", "order": 47}, {"cast_id": 206, "character": "Head of Nation", "credit_id": "56fddfef9251412a54000ba8", "gender": 2, "id": 1599260, "name": "Wai Wong", "order": 48}, {"cast_id": 207, "character": "Head of Nation", "credit_id": "56fde0179251412a47000ac2", "gender": 2, "id": 1477143, "name": "Joseph Balderrama", "order": 49}, {"cast_id": 208, "character": "Aide", "credit_id": "56fde0809251416cc20000cb", "gender": 2, "id": 1599261, "name": "Eiji Mihara", "order": 50}, {"cast_id": 209, "character": "Aide", "credit_id": "56fde0a49251412a47000ae0", "gender": 2, "id": 1168129, "name": "Junichi Kajioka", "order": 51}, {"cast_id": 40, "character": "Clinic Barman", "credit_id": "56486850c3a368260c006ecf", "gender": 0, "id": 48393, "name": "Victor Schef\\u00e9", "order": 52}, {"cast_id": 210, "character": "Clinic Security Guard", "credit_id": "56fde0f19251412a42000c28", "gender": 2, "id": 1437333, "name": "Harald Windisch", "order": 53}, {"cast_id": 211, "character": "Clinic Security Guard", "credit_id": "56fde118c3a36821a4000c3c", "gender": 2, "id": 1599262, "name": "Tristan Matthiae", "order": 54}, {"cast_id": 177, "character": "Cable Car Heavy", "credit_id": "5696db21c3a3683af90002d6", "gender": 2, "id": 14637, "name": "Detlef Bothe", "order": 55}, {"cast_id": 212, "character": "Cable Car Heavy", "credit_id": "56fde128c3a368219d000b4f", "gender": 2, "id": 1599263, "name": "Bodo Friesecke", "order": 56}, {"cast_id": 213, "character": "Syringe Heavy", "credit_id": "56fde1769251412a54000c0b", "gender": 2, "id": 1599264, "name": "Wilhem Iben", "order": 57}, {"cast_id": 214, "character": "Snowboarder", "credit_id": "56fde1849251412a42000c4d", "gender": 1, "id": 1599265, "name": "Noemi Krausz", "order": 58}, {"cast_id": 215, "character": "Snowboarder", "credit_id": "56fde18dc3a36821b6000c4f", "gender": 2, "id": 1599266, "name": "Noah Saavedra", "order": 59}, {"cast_id": 216, "character": "Snowboarder", "credit_id": "56fde1989251412a54000c16", "gender": 0, "id": 1599267, "name": "Francis Attakpah", "order": 60}, {"cast_id": 217, "character": "Snowboarder", "credit_id": "56fde1a39251412a42000c58", "gender": 2, "id": 1599268, "name": "Michael Glantschnig", "order": 61}, {"cast_id": 218, "character": "Snowboarder", "credit_id": "56fde1aec3a36821ab000cbf", "gender": 2, "id": 1599269, "name": "Marlon Boess", "order": 62}, {"cast_id": 219, "character": "Snowboarder", "credit_id": "56fde1b8c3a36821ae000c62", "gender": 1, "id": 1599270, "name": "Marie Wohlmuth", "order": 63}, {"cast_id": 220, "character": "Snowboarder", "credit_id": "56fde1c1c3a36821b1000c9c", "gender": 1, "id": 1599271, "name": "Lili Epply", "order": 64}, {"cast_id": 221, "character": "Snowboarder", "credit_id": "56fde1cbc3a36821a7000baf", "gender": 2, "id": 1599272, "name": "Konstantin Gerlach", "order": 65}, {"cast_id": 222, "character": "L\'Americain Manater", "credit_id": "56fde24c9251412a45000bfb", "gender": 1, "id": 1102369, "name": "Lara Parmiani", "order": 66}, {"cast_id": 223, "character": "Train Guard", "credit_id": "56fde2679251412a54000c42", "gender": 2, "id": 1372694, "name": "Umit Ulgen", "order": 67}, {"cast_id": 224, "character": "Train Waiter", "credit_id": "56fde2869251412a50000bf1", "gender": 2, "id": 1363060, "name": "Amra Mallassi", "order": 68}, {"cast_id": 225, "character": "Train Barman", "credit_id": "56fde2969251412a45000c15", "gender": 2, "id": 1599275, "name": "Ziad Abaza", "order": 69}, {"cast_id": 226, "character": "Blofeld\'s Chauffeur", "credit_id": "56fde2a79251412a54000c55", "gender": 2, "id": 1599276, "name": "Walid Mumuni", "order": 70}, {"cast_id": 227, "character": "Blofeld\'s Guard", "credit_id": "56fde2eb9251416cc200015b", "gender": 0, "id": 1599277, "name": "Derek Horsham", "order": 71}, {"cast_id": 228, "character": "Blofeld\'s Guard", "credit_id": "56fde3059251412a47000b6a", "gender": 2, "id": 229320, "name": "Nari Blair-Mangat", "order": 72}, {"cast_id": 229, "character": "Blofeld\'s Butler", "credit_id": "56fde321c3a36821ab000d32", "gender": 0, "id": 1599278, "name": "Michael White", "order": 73}, {"cast_id": 230, "character": "Blofeld\'s Waiter", "credit_id": "56fde34c9251412a56000c21", "gender": 0, "id": 1599279, "name": "Adam McGrady", "order": 74}, {"cast_id": 231, "character": "Blofeld\'s Analyst", "credit_id": "56fde36d9251412a50000c2b", "gender": 2, "id": 1436816, "name": "Nader Dernaika", "order": 75}, {"cast_id": 232, "character": "Blofeld\'s Chief Analyst", "credit_id": "56fde37f9251412a4b000cf7", "gender": 2, "id": 1599280, "name": "Pezhmaan Alinia", "order": 76}, {"cast_id": 31, "character": "M (uncredited)", "credit_id": "562f218fc3a3681b5200c9e5", "gender": 1, "id": 5309, "name": "Judi Dench", "order": 77}, {"cast_id": 26, "character": "Clinic Patron (uncredited)", "credit_id": "5517b4bbc3a3686302002f36", "gender": 1, "id": 1186597, "name": "Neve Gachev", "order": 78}, {"cast_id": 245, "character": "Businessman (uncredited)", "credit_id": "57e11a3e92514104570052ba", "gender": 2, "id": 1654739, "name": "Karl Farrer", "order": 79}, {"cast_id": 246, "character": "Lair Staff (uncredited)", "credit_id": "57e124d992514104530055ec", "gender": 1, "id": 1682535, "name": "Kim Adis", "order": 80}, {"cast_id": 247, "character": "Mexican Sprite (uncredited)", "credit_id": "57e125ccc3a36853f2005365", "gender": 1, "id": 1682536, "name": "Maurisa Selene Coleman", "order": 81}, {"cast_id": 249, "character": "Pilot David", "credit_id": "585ab69fc3a3682fb8091219", "gender": 2, "id": 1725801, "name": "Matija Mondi Matovi\\u0107", "order": 82}]'

In [39]:
def convert_cast(obj):
    counter = 0
    X = []
    for i in ast.literal_eval(obj):
        if counter !=3:
            X.append(i['name'])
            counter += 1
        else:
            break
    return X

In [40]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [41]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [42]:
def director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [44]:
movies['crew'] = movies['crew'].apply(director)

In [45]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [46]:
movies['overview'] = movies['overview'].apply(lambda x:x if isinstance(x, list) else [ x ])

In [47]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In the 22nd century, a paraplegic Marine is d...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,[A cryptic message from Bondâ€™s past sends him ...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,[Following the death of District Attorney Harv...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John Carter is a war-weary, former military c...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [48]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [49]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In the 22nd century, a paraplegic Marine is d...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,[A cryptic message from Bondâ€™s past sends him ...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,[Following the death of District Attorney Harv...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John Carter is a war-weary, former military c...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [50]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [51]:
new_df = movies[['movie_id', 'title', 'tags']]

In [52]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In the 22nd century, a paraplegic Marine is d..."
1,285,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h..."
2,206647,Spectre,[A cryptic message from Bondâ€™s past sends him ...
3,49026,The Dark Knight Rises,[Following the death of District Attorney Harv...
4,49529,John Carter,"[John Carter is a war-weary, former military c..."

In [53]:
 new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(map(str, x)))

C:\Users\saivi\AppData\Local\Temp\ipykernel_4576\2998033873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(map(str, x)))

In [55]:
new_df['tags'][3]

"Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy. Action Crime Drama Thriller dccomics crimefighter terrorist secretidentity burglar hostagedrama timebomb gothamcity vigilante cover-up superhero villainess tragichero terrorism destruction catwoman catburglar imax flood criminalunderworld batman ChristianBale MichaelCaine GaryOldman ChristopherNolan"

In [56]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\saivi\AppData\Local\Temp\ipykernel_4576\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [62]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [64]:
vectors.shape

(4809, 5000)

In [86]:
import nltk

In [88]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [89]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [90]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\saivi\AppData\Local\Temp\ipykernel_4576\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [91]:
new_df['tags'] [1200]

"dale, kurt and nick decid to start their own busi but thing don't go as plan becaus of a slick investor, prompt the trio to pull off a harebrain and misguid kidnap scheme. comedi prison kidnap sequel carchas sexaddict sextap jasonbateman jasonsudeiki charlieday seanand"

In [92]:
cv.get_feature_names()

C:\Users\saivi\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '18thcentury',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'amazon',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americanfootballplayer',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusement',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashes',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attempttoescape',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'bid',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikers',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhinds',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdifferences',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 ...]

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
similarity = cosine_similarity(vectors)

In [67]:
similarity

array([[1.        , 0.08980265, 0.05892557, ..., 0.0248452 , 0.02777778,
        0.        ],
       [0.08980265, 1.        , 0.06350006, ..., 0.02677398, 0.        ,
        0.        ],
       [0.05892557, 0.06350006, 1.        , ..., 0.02635231, 0.        ,
        0.        ],
       ...,
       [0.0248452 , 0.02677398, 0.02635231, ..., 1.        , 0.0745356 ,
        0.04774099],
       [0.02777778, 0.        , 0.        , ..., 0.0745356 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05337605,
        1.        ]])

In [70]:
new_df[new_df['title'] == 'The Lego Movie'].index[0]

744

In [79]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [97]:
recommend("The Dark Knight Rises")

The Dark Knight
Batman Begins
Batman
Batman Returns
Batman